2024-05-09 12:33:43,743 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username1', 'pbkdf2:sha256:600000$v6SEsJ9QtAtqQJNf$62928bfe8d18649ab22be16f0b43558be9f070bd6dfc00004e3da60e0e3a160d', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 13:06:05,193 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username1', 'pbkdf2:sha256:600000$4So9EXQZRXkK0JoU$02d42406ca7c3e39e0ccd2cc01dc03207456a7f805d41b2301edbca86b2e4592', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 13:14:26,026 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username3', 'pbkdf2:sha256:600000$GrMhKD55vf2BhEV9$ddd56ed719c3122b64c6083fb585e0ae74ae6844866ad8155446e88a2a12779b', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 14:04:23,633 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username100', 'pbkdf2:sha256:600000$tFBqk8Fv31pf8eq1$b2fb59a75da21b7cb6980a648f9cbceba818ab2ff9b749803bfd4e0aec29b6de', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 14:26:44,447 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'rizkymirza18@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username101', 'pbkdf2:sha256:600000$ZX1vTWFAXX0aDl7u$567ca0776559e8db0ffadc52c42106471ad7a48cfe9ead9a043cb0fdf10d0c0e', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'rizkymirza18@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:27:04,290 ERROR: Failed to send email: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:117]
2024-05-09 14:27:04,291 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:27:31,528 ERROR: Failed to send email: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:117]
2024-05-09 14:27:31,529 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:01,967 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'earthtoalvido@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$SoKuvcYwfQJZgY0K$b254adcae68116eebffa2ae8dac60854e21a26f333c63977de896a21e55637d9', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'earthtoalvido@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:10,458 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'earthtoalvd@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$PtJIhTQ87EPUA3hy$ead7e2dc199e152888c11cdf6c6db5235a60aef1e2c3ed373759730006f6f433', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'earthtoalvd@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:30,119 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$5TAl4i1miM162xx1$32df82fc8c4fd2c292b83317bb868fbf5768b82445a0b6f2dcc2368d9b05e900', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-10 02:25:30,273 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:18:39,504 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:20:55,676 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:22:41,711 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:23:47,908 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:24:23,276 ERROR: Exception occurred: features/auth/templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:25:23,480 ERROR: Exception occurred: features/auth/templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:25:52,168 ERROR: Exception occurred: templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 17:55:10,690 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:140]
2024-05-10 17:57:41,149 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is Suspend. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is Suspend.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:140]
